### ISSUE TITLE
Is it possible to install this extension through argocd-apps helm chart?

### ISSUE THREAD

**Issue by autokilla47** [argoproj-labs/argocd-extension-metrics#12]
![image](https://user-images.githubusercontent.com/49757910/209654342-34cff855-7dd6-4805-8aa4-ae60cf49d366.png)
I deploy ArgoCD (ver: v2.5.5) from argo-cd helm chart, set `server.extensions.enabled: true`.
Create argocd-metrics-server deployment in argocd namespace.
Deploy ArgoCD apps from argocd-apps helm chart when set extensions like on a picture.
In logs from container (ghcr.io/argoproj-labs/argocd-extensions:v0.2.1) i see just:
`2022-12-27T10:31:23.268Z	INFO	controller.argocdextension	Sources already downloaded.	{"reconciler group": "argoproj.io", "reconciler kind": "ArgoCDExtension", "name": "argocd-extension-metrics", "namespace": "argocd"}`
Extension tab in AgroCD UI not showing up.
Am I installing the extension incorrectly?

Upgrade: changet to:
```
  sources:
    - web:
        url: https://github.com/argoproj-labs/argocd-extension-metrics/blob/main/manifests/extension.tar
```
and use `image: sarabala1979/argocd-metrics-server:latest`
ingress like this:
```
spec:
  ingressClassName: nginx
  rules:
    - host: my-argocd.info
      http:
        paths:
          - path: /extensions/metrics
            pathType: Prefix
            backend:
              service:
                name: argocd-metrics-server
                port:
                  number: 9003
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
```
