### ISSUE TITLE
Metrics request is returning 404 

### ISSUE THREAD

**Issue by Jojoooo1** [argoproj-labs/argocd-extension-metrics#68]
### Describe the bug

Helm chart version: 5.52.2 (https://github.com/Jojoooo1/argo-deploy-applications-infra/blob/main/argo-apps/base/argocd-helm.yaml)
ArgoCD extension metrics: main branch using Kustomize

Configuration:
```yaml
[...]
configs:
 cm:
   extension.config: |-
    extensions:
      - name: metrics
        backend:
          services:
            - url: http://prometheus-operated.observability.svc.cluster.local:9090

  rbac:
    policy.default: role:readonly
    policy.csv: |-
      p, role:readonly, extensions, invoke, metrics, allow
      p, role:admin, extensions, invoke, metrics, allow
[...]
server:
  extensions:
    enabled: true
    extensionList:
      - name: extension-metrics
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension.tar.gz
          - name: EXTENSION_CHECKSUM_URL
            value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension_checksums.txt
```

When trying to get the dashboard, it is returning 404:

![Screenshot from 2024-01-19 10-53-10](https://github.com/argoproj-labs/argocd-extension-metrics/assets/17641873/365d9c43-de20-47c5-bc3d-1d09d1ebaa5a)

Server logs:
```
time="2024-01-19T14:05:35Z" level=info msg="Querying for resource events with field selector: involvedObject.uid=059de200-44fa-4d9b-8b75-cec9f2559286,involvedObject.namespace=argocd,involvedObject.name=argocd-server-6bc88dbf77-gmhxl"

time="2024-01-19T14:05:35Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListResourceEvents grpc.service=application.ApplicationService grpc.start_time="2024-01-19T14:05:35Z" grpc.time_ms=11.854 span.kind=server system=grpc
```

**Comment by Tchoupinax** [comment]
Same!

**Comment by Jojoooo1** [comment]
my mistake 
```
              extensions:
                - name: metrics
                  backend:
                    services:
                    - url: http://argocd-metrics-server.argocd.svc.cluster.local:9003
```
