### ISSUE TITLE
Big Docs Mistake..?

### ISSUE THREAD

**Issue by ForbiddenEra** [argoproj-labs/argocd-extension-metrics#73]
Docs say to use:

```
policy.csv: |-
  p, role:readonly, extensions, invoke, httpbin, allow
```

And I get `No metrics available` .. check my logs, says I'm not authorized to use extension `metrics` (even though I'm admin)

so I go hmm...
```
policy.csv: |-
  p, role:admin, extensions, invoke, httpbin, allow
```

Still no go.. so I go hmmmmmmmmmmm........

```
policy.csv: |-
  p, role:admin, extensions, invoke, metrics, allow
```

annnnnnd whatdoyaknow?! BAM
![image](https://github.com/argoproj-labs/argocd-extension-metrics/assets/7980490/9bcb7f32-deb9-4d34-85e4-04ce62f4cb1e)

so where did `httpbin` come from? I'm using basically exactly the default config..?

The docs also show:
```
extension.config: |-
  extensions:
    - name: metrics
      backend:
        services:
          - url: <METRICS_SERVER_URL>
```

and https://argo-cd.readthedocs.io/en/stable/developer-guide/extensions/proxy-extensions/ shows:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  extension.config: |
    extensions:
    - name: httpbin
      backend:
        connectionTimeout: 2s
        keepAlive: 15s
        idleConnectionTimeout: 60s
        maxIdleConnections: 30
        services:
        - url: http://httpbin.org
          headers:
          - name: some-header
            value: '$some.argocd.secret.key'
          cluster:
            name: some-cluster
            server: https://some-cluster
```

as an example for proxy extensions...... Did someone just copy/paste and forget to update RBAC to `metrics` or something?
