### ISSUE TITLE
quickstart instructions exclude configmap.yaml, also need installation instructions

### ISSUE THREAD

**Issue by bkcsfi** [argoproj-labs/argocd-extension-metrics#8]
these instructions don't work

```
kubectl apply -n argocd \
    -f https://raw.githubusercontent.com/argoproj-labs/argocd-extension-metrics/main/manifests/install.yaml
```
because manifests/configmap.yaml does not get installed.

As a workaround, the configmap can be installed as a distinct resource:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-extension-metrics/main/manifests/configmap.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-extension-metrics/main/manifests/install.yaml
```

I have installed argocd extensions, metrics server and metrics extension. I also restarted argocd server, but the metrics tab does not appear in argocd. 

Are there additional installation steps needed that haven't been documented?

**Comment by bkanuka** [comment]
From the config, it looks like argocd-extension-metrics is looking for a prometheus server at: `prometheus-service.monitoring.svc.cluster.local`.  Makes me belive that this extension needs prometheus installed.  I also haven't gotten it to work yet however.

**Comment by nikhilgorantla** [comment]
Changing metrics end point also doesn't work all i see on pod logs 

`[GIN-debug] GET    /                         --> github.com/sarabala1979/argo-observability/server.(*O11yServer).Run.func1 (3 handlers)                                                                                                                     │
│ [GIN-debug] GET    /api/extension/o11y/applications/:application/groupkinds/:groupkind/rows/:row/graphs/:graph --> github.com/sarabala1979/argo-observability/server.(*O11yServer).queryMetrics-fm (3 handlers)                                             │
│ [GIN-debug] GET    /api/extension/o11y/applications/:application/groupkinds/:groupkind/dashboards --> github.com/sarabala1979/argo-observability/server.(*O11yServer).dashboardConfig-fm (3 handlers)`

**Comment by otherguy** [comment]
I'm running this on GKE with managed prometheus, but I don't know how to configure the extension to make use of that. The tab isn't showing up regardless.

**Comment by zek** [comment]
I managed to show tab however charts are empty

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/3463291/221325920-62c436df-9389-459b-bb2a-e5a4499d55c6.png">

What I did so far

1. Use raw extension.tar https://github.com/argoproj-labs/argocd-extension-metrics/raw/main/manifests/extension.tar
2. update container image into sarabala1979/argocd-metrics-server:latest in `install.yaml`
3. strip prefix `/extensions/metrics`

in case you are using traefik
4. add `traefik.ingress.kubernetes.io/service.serversscheme: https` into service definition
5. add `--serverstransport.insecureskipverify=true`

I see that this extension is not ready yet and still in development. 

I'm newbie to kubernetes so I don't know what to do next to export metrics to prometheus.

**Comment by sarabala1979** [comment]
@zek Great. can you share your configmap and metrics server log?

**Comment by autokilla47** [comment]
> I also haven't gotten it to work yet however.

I have an external prometues and I set its address, but without results.

**Comment by SnoozeFreddo** [comment]
Same here

**Comment by sarabala1979** [comment]
@SnoozeFreddo Have you configured prometheus URL on configmap?
https://github.com/argoproj-labs/argocd-extension-metrics/blob/68f2063a538627f5a49905d66c00b8c711a2f5e1/manifests/configmap.yaml#L299

**Comment by SnoozeFreddo** [comment]
No i didn't. Thank you.

**Comment by otherguy** [comment]
> > I also haven't gotten it to work yet however.
> 
> I have an external prometues and I set its address, but without results.

Same here. Using GKE managed Prometheus.

**Comment by mehdicopter** [comment]
> > > I also haven't gotten it to work yet however.
> > 
> > 
> > I have an external prometues and I set its address, but without results.
> 
> Same here. Using GKE managed Prometheus.

I am working on it and will let you know on results ;)

**Comment by mehdicopter** [comment]
I have a prometheus proxy to GMP deployed in monitoring namespace, here is my `config.json`

```yaml
config.json: |
    {
      "prometheus": {
        "applications": [
          {
            "name": "default",
            "default": true,
            "dashboards": [
              {
                "groupKind": "pod",
                "tabs": [
                  "Golden Signal"
                ],
                "rows": [
                  {
                    "name": "pod",
                    "title": "Pods",
                    "tab": "Golden Signal",
                    "graphs": [
                      {
                        "name": "pod_cpu_line",
                        "title": "CPU",
                        "description": "",
                        "graphType": "line",
                        "metricName": "pod",
                        "queryExpression": "sum(rate(kubernetes_io:container_cpu_core_usage_time{pod_name=~\"{{.name}}\", image!=\"\", container!=\"POD\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod_name)"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ],
        "provider": {
          "Name": "default",
          "default": true,
          "address": "http://prometheus.monitoring:9090"
        }
      }
    }
```

Yet i have no results...
