### ISSUE TITLE
Can not use url in local cluster

### ISSUE THREAD

**Issue by PhamQuang-512** [argoproj-labs/argocd-extension-metrics#82]
i have set metrics url to argocd-metrics-server.argocd.svc.cluster.local but it seem not work. argocd-server and argocd-metrics-server do not show any logs.
here is my config:
    extension.config: |-
      extensions:
        - name: metrics
          backend:
            services:
              - url: argocd-metrics-server.argocd.svc.cluster.local

**Comment by ghost** [comment]
@PhamQuang-512 try with port
like this :  "http://argocd-metrics-server.argocd.svc.cluster.local:9003"
it should work...

**Comment by PhamQuang-512** [comment]
> @PhamQuang-512 try with port like this : "http://argocd-metrics-server.argocd.svc.cluster.local:9003" it should work...

yeah it works, but now there is no metrics no show 
![image](https://github.com/user-attachments/assets/6c488a8b-bb0a-4e3f-a332-1674876f4494)
![image](https://github.com/user-attachments/assets/bbfb778f-2df9-4530-95c9-93a8f819cdd6)

logs from metrics server:
```
[GIN] 2024/08/16 - 04:16:55 | 200 |      221.72µs |       127.0.0.1 | GET      "/api/applications/my-test-application-helm/groupkinds/pod/dashboards"
pod pod
[GIN] 2024/08/16 - 04:16:55 | 400 |   21.117186ms |       127.0.0.1 | GET      "/api/applications/my-test-application-helm/groupkinds/pod/rows/pod/graphs/pod_cpu_line?name=my-test-application-helm-test-chart-65b6455984-8dtb7.*&namespace=default&application_name=my-test-application-helm&project=default&uid=309a31b3-4f93-46c8-b5ca-5af42cb024ad&duration=1h"
pod pod
[GIN] 2024/08/16 - 04:16:55 | 400 |    2.263399ms |       127.0.0.1 | GET      "/api/applications/my-test-application-helm/groupkinds/pod/rows/pod/graphs/pod_cpu_pie?name=my-test-application-helm-test-chart-65b6455984-8dtb7.*&namespace=default&application_name=my-test-application-helm&project=default&uid=309a31b3-4f93-46c8-b5ca-5af42cb024ad&duration=1h"
pod pod
[GIN] 2024/08/16 - 04:16:55 | 400 |     2.22914ms |       127.0.0.1 | GET      "/api/applications/my-test-application-helm/groupkinds/pod/rows/pod/graphs/pod_memory_line?name=my-test-application-helm-test-chart-65b6455984-8dtb7.*&namespace=default&application_name=my-test-application-helm&project=default&uid=309a31b3-4f93-46c8-b5ca-5af42cb024ad&duration=1h"
pod pod
[GIN] 2024/08/16 - 04:16:55 | 400 |     1.92753ms |       127.0.0.1 | GET      "/api/applications/my-test-application-helm/groupkinds/pod/rows/pod/graphs/pod_memory_pie?name=my-test-application-helm-test-chart-65b6455984-8dtb7.*&namespace=default&application_name=my-test-application-helm&project=default&uid=309a31b3-4f93-46c8-b5ca-5af42cb024ad&duration=1h"
pod pod
[GIN] 2024/08/16 - 04:16:56 | 400 |     2.23645ms |       127.0.0.1 | GET      "/api/applications/my-test-application-helm/groupkinds/pod/rows/container/graphs/container_cpu_line?name=my-test-application-helm-test-chart-65b6455984-8dtb7.*&namespace=default&application_name=my-test-application-helm&project=default&uid=309a31b3-4f93-46c8-b5ca-5af42cb024ad&duration=1h"
pod pod
[GIN] 2024/08/16 - 04:16:56 | 400 |    2.068919ms |       127.0.0.1 | GET      "/api/applications/my-test-application-helm/groupkinds/pod/rows/container/graphs/container_cpu_pie?name=my-test-application-helm-test-chart-65b6455984-8dtb7.*&namespace=default&application_name=my-test-application-helm&project=default&uid=309a31b3-4f93-46c8-b5ca-5af42cb024ad&duration=1h"
pod pod
[GIN] 2024/08/16 - 04:16:56 | 400 |     2.14581ms |       127.0.0.1 | GET      "/api/applications/my-test-application-helm/groupkinds/pod/rows/container/graphs/container_memory_line?name=my-test-application-helm-test-chart-65b6455984-8dtb7.*&namespace=default&application_name=my-test-application-helm&project=default&uid=309a31b3-4f93-46c8-b5ca-5af42cb024ad&duration=1h"
pod pod
[GIN] 2024/08/16 - 04:16:56 | 400 |     2.09328ms |       127.0.0.1 | GET      "/api/applications/my-test-application-helm/groupkinds/pod/rows/container/graphs/container_memory_pie?name=my-test-application-helm-test-chart-65b6455984-8dtb7.*&namespace=default&application_name=my-test-application-helm&project=default&uid=309a31b3-4f93-46c8-b5ca-5af42cb024ad&duration=1h"
```

**Comment by ghost** [comment]
@PhamQuang-512 can you share sample of your configmap.

**Comment by PhamQuang-512** [comment]
> @PhamQuang-512 can you share sample of your configmap.

sure, this is my configmap:
`  cm:
    kustomize.buildOptions: "--enable-alpha-plugins"
    application.resourceTrackingMethod: annotation
    exec.enabled: true
    admin.enabled: true
    dex.config: |
      connectors:
      - config:
          issuer: $ISSUER
          clientID: $CLIENT_ID
          clientSecret: $CLIENT_SECRET
        type: oidc
        id: google
        name: Google
    url: http://localhost:8080
    extension.config: |-
      extensions:
        - name: metrics
          backend:
            services:
              - url: "http://argocd-metrics-server.argocd.svc.cluster.local:9003"
  params:
    server.insecure: true
    server.enable.proxy.extension: "true"
    controller.sharding.algorithm: "consistent-hashing"`

**Comment by PhamQuang-512** [comment]
> @PhamQuang-512 can you share sample of your configmap.

sure, this is my configmap:

```
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins"
    application.resourceTrackingMethod: annotation
    exec.enabled: true
    admin.enabled: true
    dex.config: |
      connectors:
      - config:
          issuer: $ISSUER
          clientID: $CLIENT_ID
          clientSecret: $CLIENT_SECRET
        type: oidc
        id: google
        name: Google
    url: http://localhost:8080
    extension.config: |-
      extensions:
        - name: metrics
          backend:
            services:
              - url: "http://argocd-metrics-server.argocd.svc.cluster.local:9003"
  params:
    server.insecure: true
    server.enable.proxy.extension: "true"
    controller.sharding.algorithm: "consistent-hashing"
```
