### ISSUE TITLE
Using paths (for reverse proxy)

### ISSUE THREAD

**Issue by agray-ctm** [argoproj-labs/argocd-extension-metrics#85]
At the company I work for, we use a reverse proxy for any APIs, and subdomains for UIs.

When given a path i.e. "https://api_url.com/argocd-extension-metrics" which reverse proxies to the service, argocd-extension-metrics does not work.

I have tested both with and without the reverse proxy, and the responses are exactly the same so there's no reason it shouldn't work. In the meantime, I set up a subdomain purely to run this extension which is a bit stupid. Works fine, but doesn't fit into our ways of working and isn't clean.

**Comment by marcelofabricanti** [comment]
I didn't create an Ingress to externsion-metrics here.
Just configure like below and argocd-server will communicate with externsion-metrics by inside of cluster.

argocd-cm
```
  extension.config: |
    extensions:
     - name: metrics
       backend:
         services:
           - url: http://argocd-metrics-server.argocd.svc.cluster.local:9003 
```

argocd-cmd-params-cm
```
server.enable.proxy.extension: 'true'
``` 

remember to set RBAC correctly:
`
p, role:authenticated, extensions, invoke, metrics, allow
`
